## Transformaciones

Usaremos el dataset del Inegi para esta sección. El dataset de Taxis de NY se usará tanto en los ejericicos así como opción para el proyecto final.

In [1]:
import polars as pl

with open('../data/inegi.csv', 'r', encoding='latin1') as fh:
    polars_df = pl.read_csv(fh.read().encode('utf-8')) 
polars_df.head()

shape: (5, 42)
┌─────────┬─────────────┬─────────┬──────────┬─────┬──────────┬────────────┬────────────┬──────────┐
│ id      ┆ clee        ┆ nom_est ┆ raz_soci ┆ ... ┆ tipoUniE ┆ latitud    ┆ longitud   ┆ fecha_al │
│ ---     ┆ ---         ┆ ab      ┆ al       ┆     ┆ co       ┆ ---        ┆ ---        ┆ ta       │
│ i64     ┆ str         ┆ ---     ┆ ---      ┆     ┆ ---      ┆ f64        ┆ f64        ┆ ---      │
│         ┆             ┆ str     ┆ str      ┆     ┆ str      ┆            ┆            ┆ str      │
╞═════════╪═════════════╪═════════╪══════════╪═════╪══════════╪════════════╪════════════╪══════════╡
│ 6174829 ┆ 20169114119 ┆ PESCA   ┆ null     ┆ ... ┆ Fijo     ┆ 18.255652  ┆ -96.614697 ┆ 2010-07  │
│         ┆ 00100100000 ┆ DE CRUS ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆ 0000U7      ┆ TÁCEOS, ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ MOLUSCO ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ S Y ... ┆          ┆     ┆          ┆            ┆            ┆          │
│ 6174806 ┆ 20406114119 ┆ PESCA   ┆ null     ┆ ... ┆ Fijo     ┆ 18.313758  ┆ -96.647255 ┆ 2010-07  │
│         ┆ 00039100000 ┆ DE CRUS ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆ 0000U9      ┆ TÁCEOS, ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ MOLUSCO ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ S Y ... ┆          ┆     ┆          ┆            ┆            ┆          │
│ 6174723 ┆ 20406114119 ┆ PESCA   ┆ null     ┆ ... ┆ Fijo     ┆ 18.313758  ┆ -96.647255 ┆ 2010-07  │
│         ┆ 00034100000 ┆ DE CRUS ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆ 0000U4      ┆ TÁCEOS, ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ MOLUSCO ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ S Y ... ┆          ┆     ┆          ┆            ┆            ┆          │
│ 6174722 ┆ 20309114119 ┆ PESCA   ┆ null     ┆ ... ┆ Fijo     ┆ 18.136119  ┆ -96.520094 ┆ 2010-07  │
│         ┆ 00078100000 ┆ DE CRUS ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆ 0000U7      ┆ TÁCEOS, ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ MOLUSCO ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ S Y ... ┆          ┆     ┆          ┆            ┆            ┆          │
│ 6174801 ┆ 20406114119 ┆ PESCA   ┆ null     ┆ ... ┆ Fijo     ┆ 18.313758  ┆ -96.647255 ┆ 2010-07  │
│         ┆ 00038100000 ┆ DE CRUS ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆ 0000U0      ┆ TÁCEOS, ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ MOLUSCO ┆          ┆     ┆          ┆            ┆            ┆          │
│         ┆             ┆ S Y ... ┆          ┆     ┆          ┆            ┆            ┆          │
└─────────┴─────────────┴─────────┴──────────┴─────┴──────────┴────────────┴────────────┴──────────┘

Primero haremos un análisis exploratorio básico para identificar problemas en la calidad de los datos:

In [2]:
polars_df.describe()

shape: (7, 43)
┌────────────┬───────────┬───────────┬─────────┬─────┬──────────┬───────────┬───────────┬──────────┐
│ describe   ┆ id        ┆ clee      ┆ nom_est ┆ ... ┆ tipoUniE ┆ latitud   ┆ longitud  ┆ fecha_al │
│ ---        ┆ ---       ┆ ---       ┆ ab      ┆     ┆ co       ┆ ---       ┆ ---       ┆ ta       │
│ str        ┆ f64       ┆ str       ┆ ---     ┆     ┆ ---      ┆ f64       ┆ f64       ┆ ---      │
│            ┆           ┆           ┆ str     ┆     ┆ str      ┆           ┆           ┆ str      │
╞════════════╪═══════════╪═══════════╪═════════╪═════╪══════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 22010.0   ┆ 22010     ┆ 22010   ┆ ... ┆ 22010    ┆ 22010.0   ┆ 22010.0   ┆ 22010    │
│ null_count ┆ 0.0       ┆ 0         ┆ 0       ┆ ... ┆ 0        ┆ 0.0       ┆ 0.0       ┆ 0        │
│ mean       ┆ 6.8814e6  ┆ null      ┆ null    ┆ ... ┆ null     ┆ 20.625223 ┆ -99.22675 ┆ null     │
│            ┆           ┆           ┆         ┆     ┆          ┆           ┆ 6         ┆          │
│ std        ┆ 1.3269e6  ┆ null      ┆ null    ┆ ... ┆ null     ┆ 3.619234  ┆ 6.792572  ┆ null     │
│ min        ┆ 70136.0   ┆ 010011125 ┆ 11 DE   ┆ ... ┆ Fijo     ┆ 14.5406   ┆ -117.0509 ┆ 2010-07  │
│            ┆           ┆ 120000320 ┆ DICIEMB ┆     ┆          ┆           ┆ 87        ┆          │
│            ┆           ┆ 00000000U ┆ RE DE   ┆     ┆          ┆           ┆           ┆          │
│            ┆           ┆ 9         ┆ 1996    ┆     ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ SPR DE  ┆     ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ R...    ┆     ┆          ┆           ┆           ┆          │
│ max        ┆ 9.3908e6  ┆ 320581141 ┆ ZUAREV  ┆ ... ┆ Semifijo ┆ 32.668645 ┆ -86.73195 ┆ 2022-11  │
│            ┆           ┆ 190000910 ┆ SPR DE  ┆     ┆          ┆           ┆ 7         ┆          │
│            ┆           ┆ 00000000U ┆ RL      ┆     ┆          ┆           ┆           ┆          │
│            ┆           ┆ 3         ┆         ┆     ┆          ┆           ┆           ┆          │
│ median     ┆ 6.180787e ┆ null      ┆ null    ┆ ... ┆ null     ┆ 19.396217 ┆ -97.84662 ┆ null     │
│            ┆ 6         ┆           ┆         ┆     ┆          ┆           ┆ 5         ┆          │
└────────────┴───────────┴───────────┴─────────┴─────┴──────────┴───────────┴───────────┴──────────┘

In [6]:
pl.Config.set_tbl_rows(15)
cols = ('tipo_v_e_1','nom_v_e_1','tipo_v_e_2','nom_v_e_2','tipo_v_e_3','nom_v_e_2','tipo_vial','nom_vial')
for column in cols:
    print(polars_df.groupby(column).agg(pl.count()).select([column,'count']).sort('count').tail(15))

shape: (15, 2)
┌────────────────────┬───────┐
│ tipo_v_e_1         ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u32   │
╞════════════════════╪═══════╡
│ PERIFERICO         ┆ 13    │
│ CALZADA            ┆ 22    │
│ PROLONGACION       ┆ 25    │
│ null               ┆ 45    │
│ CERRADA            ┆ 60    │
│ ANDADOR            ┆ 63    │
│ PEATONAL           ┆ 88    │
│ BOULEVARD          ┆ 89    │
│ PASAJE             ┆ 217   │
│ PRIVADA            ┆ 328   │
│ CALLEJON           ┆ 354   │
│ CARRETERA          ┆ 807   │
│ AVENIDA            ┆ 835   │
│ OTRO (ESPECIFIQUE) ┆ 5988  │
│ CALLE              ┆ 13054 │
└────────────────────┴───────┘
shape: (15, 2)
┌─────────────────┬───────┐
│ nom_v_e_1       ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ LAZARO CARDENAS ┆ 56    │
│ 20              ┆ 57    │
│ 14              ┆ 57    │
│ NINGUNA         ┆ 92    │
│ VECINAL         ┆ 102   │
│ EMILIANO ZAPATA ┆ 130   │
│ ninguno         ┆ 153   │
│ BENITO JUAREZ   ┆ 174   │
│ 5               ┆ 256   │
│ PRINCIPAL       ┆ 258   │
│ null            ┆ 276   │
│ SIN REFERENCIA  ┆ 288   │
│ Ninguno         ┆ 385   │
│ SIN NOMBRE      ┆ 701   │
│ NINGUNO         ┆ 10578 │
└─────────────────┴───────┘
shape: (15, 2)
┌────────────────────┬───────┐
│ tipo_v_e_2         ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u32   │
╞════════════════════╪═══════╡
│ CALZADA            ┆ 14    │
│ PERIFERICO         ┆ 16    │
│ PROLONGACION       ┆ 30    │
│ null               ┆ 45    │
│ PEATONAL           ┆ 54    │
│ ANDADOR            ┆ 56    │
│ BOULEVARD          ┆ 68    │
│ CERRADA            ┆ 71    │
│ PASAJE             ┆ 227   │
│ PRIVADA            ┆ 313   │
│ CALLEJON           ┆ 396   │
│ CARRETERA          ┆ 592   │
│ AVENIDA            ┆ 758   │
│ OTRO (ESPECIFIQUE) ┆ 6431  │
│ CALLE              ┆ 12919 │
└────────────────────┴───────┘
shape: (15, 2)
┌─────────────────┬───────┐
│ nom_v_e_2       ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ CONOCIDO        ┆ 56    │
│ VECINAL         ┆ 59    │
│ RIO GRIJALVA    ┆ 66    │
│ 99              ┆ 70    │
│ EMILIANO ZAPATA ┆ 89    │
│ NINGUNA         ┆ 89    │
│ PRINCIPAL       ┆ 134   │
│ ninguno         ┆ 155   │
│ BENITO JUAREZ   ┆ 180   │
│ 5               ┆ 198   │
│ null            ┆ 291   │
│ SIN REFERENCIA  ┆ 336   │
│ Ninguno         ┆ 385   │
│ SIN NOMBRE      ┆ 815   │
│ NINGUNO         ┆ 11227 │
└─────────────────┴───────┘
shape: (15, 2)
┌────────────────────┬───────┐
│ tipo_v_e_3         ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u32   │
╞════════════════════╪═══════╡
│ CALZADA            ┆ 16    │
│ PEATONAL           ┆ 19    │
│ PROLONGACION       ┆ 27    │
│ PERIFERICO         ┆ 38    │
│ null               ┆ 45    │
│ CERRADA            ┆ 56    │
│ ANDADOR            ┆ 63    │
│ BOULEVARD          ┆ 75    │
│ PASAJE             ┆ 158   │
│ PRIVADA            ┆ 166   │
│ CALLEJON           ┆ 346   │
│ CARRETERA          ┆ 472   │
│ AVENIDA            ┆ 776   │
│ OTRO (ESPECIFIQUE) ┆ 7536  │
│ CALLE              ┆ 12184 │
└────────────────────┴───────┘
shape: (15, 2)
┌─────────────────┬───────┐
│ nom_v_e_2       ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ CONOCIDO        ┆ 56    │
│ VECINAL         ┆ 59    │
│ RIO GRIJALVA    ┆ 66    │
│ 99              ┆ 70    │
│ EMILIANO ZAPATA ┆ 89    │
│ NINGUNA         ┆ 89    │
│ PRINCIPAL       ┆ 134   │
│ ninguno         ┆ 155   │
│ BENITO JUAREZ   ┆ 180   │
│ 5               ┆ 198   │
│ null            ┆ 291   │
│ SIN REFERENCIA  ┆ 336   │
│ Ninguno         ┆ 385   │
│ SIN NOMBRE      ┆ 815   │
│ NINGUNO         ┆ 11227 │
└─────────────────┴───────┘
shape: (15, 2)
┌────────────────────┬───────┐
│ tipo_vial          ┆ count │
│ ---                ┆ ---   │
│ str                ┆ u32   │
╞════════════════════╪═══════╡
│ PERIFERICO         ┆ 17    │
│ null               ┆ 25    │
│ CALZADA            ┆ 32    │
│ CERRADA            ┆ 38    │
│ PROLONGACION       ┆ 61    │
│ ANDADOR            ┆ 66    │
│ PEATONAL           ┆ 73    │
│ BOULEVARD          ┆ 144   │
│ PASAJE             ┆ 189   │
│ PRIVADA            ┆ 223   │
│ CALLEJON           ┆ 288   │
│ AVENIDA            ┆ 1102  │
│ CARRETERA          ┆ 1680  │
│ OTRO (ESPECIFIQUE) ┆ 4910  │
│ CALLE              ┆ 13124 │
└────────────────────┴───────┘
shape: (15, 2)
┌─────────────────┬───────┐
│ nom_vial        ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ 20              ┆ 65    │
│ LAZARO CARDENAS ┆ 71    │
│ null            ┆ 72    │
│ MIGUEL HIDALGO  ┆ 75    │
│ O               ┆ 76    │
│ VECINAL         ┆ 80    │
│ INDEPENDENCIA   ┆ 88    │
│ Ninguno         ┆ 109   │
│ EMILIANO ZAPATA ┆ 132   │
│ BENITO JUAREZ   ┆ 134   │
│ ninguno         ┆ 140   │
│ SIN NOMBRE      ┆ 335   │
│ PRINCIPAL       ┆ 373   │
│ SIN REFERENCIA  ┆ 397   │
│ NINGUNO         ┆ 8722  │
└─────────────────┴───────┘

In [14]:
analisis_fecha = polars_df.with_columns(
    pl.concat_str([pl.col('fecha_alta'),pl.lit('01')], sep ='-')
) \
.with_columns([
        pl.col('fecha_alta').str.n_chars().alias('length')]) \
.select([pl.col('fecha_alta'),pl.col('length')])

analisis_fecha

shape: (22010, 2)
┌────────────┬────────┐
│ fecha_alta ┆ length │
│ ---        ┆ ---    │
│ str        ┆ u32    │
╞════════════╪════════╡
│ 2010-07-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ ...        ┆ ...    │
│ 2019-11-01 ┆ 10     │
│ 2019-11-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ 2014-12-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
│ 2010-07-01 ┆ 10     │
└────────────┴────────┘

In [19]:
analisis_fecha.select(pl.col('fecha_alta')
            .value_counts(sort=True)
            .alias('count_fecha_alta'))

shape: (17, 1)
┌──────────────────────┐
│ count_fecha_alta     │
│ ---                  │
│ struct[2]            │
╞══════════════════════╡
│ {"2010-07-01",10041} │
│ {"2019-11-01",5464}  │
│ {"2014-12-01",5070}  │
│ {"2020-11-01",636}   │
│ {"2020-04-01",466}   │
│ {"2016-01-01",147}   │
│ {"2019-04-01",46}    │
│ ...                  │
│ {"2011-03-01",22}    │
│ {"2017-11-01",13}    │
│ {"2022-11-01",11}    │
│ {"2021-11-01",9}     │
│ {"2013 07-01",6}     │
│ {"2012-06-01",5}     │
│ {"2021-05-01",4}     │
│ {"2017-03-01",3}     │
└──────────────────────┘

In [20]:
analisis_fecha.select(pl.col('length')
            .value_counts(sort=True)
            .alias('count_fecha_alta'))

shape: (1, 1)
┌──────────────────┐
│ count_fecha_alta │
│ ---              │
│ struct[2]        │
╞══════════════════╡
│ {10,22010}       │
└──────────────────┘

In [22]:
polars_df.select(pl.col('numero_ext').value_counts(sort=True))

shape: (952, 1)
┌─────────────┐
│ numero_ext  │
│ ---         │
│ struct[2]   │
╞═════════════╡
│ {0,11349}   │
│ {null,5342} │
│ {1,727}     │
│ {2,151}     │
│ {3,103}     │
│ {5,91}      │
│ {10,80}     │
│ ...         │
│ {752,1}     │
│ {179,1}     │
│ {451,1}     │
│ {2301,1}    │
│ {764,1}     │
│ {534,1}     │
│ {1405,1}    │
│ {578,1}     │
└─────────────┘

In [ ]:
string_nulls = ['CALLE',
                 'NINGUNO',
                 'OTRO (ESPECIFIQUE)',
                  'SIN REFERENCIA',
                  'SIN NOMBRE',
                  '0',
                  'SN',
                  'NULL']

number_nulls = [0]

In [ ]:
def rename_columns(dataframe: pl.DataFrame) -> pl.DataFrame:
    '''Takes a Polars dataframe and returns it with different column names (etl column name mapping)'''
    return dataframe.rename(
        {
            'id': 'row_number',
            'clee': 'government_business_code',
            'nom_estab': 'business_name',
            'raz_social': 'tax_business_name',
            'codigo_act': 'economic_activity_code',
            'nombre_act': 'economic_activity',
            'per_ocu': 'registered_employees_size',
            'tipo_vial': 'address_street_type',
            'nom_vial': 'address_street',
            'tipo_v_e_1': 'address_reference_type_1',
            'nom_v_e_1': 'address_reference_street_1',
            'tipo_v_e_2': 'address_reference_type_2',
            'nom_v_e_2': 'address_reference_street_2',
            'tipo_v_e_3': 'address_reference_type_3',
            'nom_v_e_3': 'address_reference_street_3',
            'numero_ext': 'address_street_number',
            'letra_ext': 'address_street_number_letter',
            'edificio': 'address_building_name',
            'edificio_e': 'address_building_floor',
            'numero_int': 'address_interior_number',
            'letra_int': 'address_interior_letter',
            'tipo_asent': 'district_type',
            'nomb_asent': 'district_name',
            'tipoCenCom': 'business_building_type',
            'nom_CenCom': 'business_building_name',
            'num_local': 'business_building_number',
            'cod_postal': 'zipcode',
            'cve_ent': 'state_code',
            'entidad': 'state',
            'cve_mun': 'municipality_code',
            'municipio': 'municipality',
            'cve_loc': 'locality_code',
            'localidad': 'locality',
            'ageb': 'address_ageb',
            'manzana': 'address_block',
            'telefono': 'telephone_number',
            'correoelec': 'email',
            'www': 'website',
            'tipoUniEco': 'economic_unit_type',
            'latitud': 'latitude',
            'longitud': 'longitude',
            'fecha_alta': 'creation_date'
        }
    )

In [ ]:
def remove_accents(dataframe: pl.DataFrame) -> pl.DataFrame:
    '''From a Polars dataframe we replace special characters in all string columns'''
    types = set(dataframe.dtypes)
    types.discard(pl.Utf8)
    dataframe = dataframe.with_columns([
        pl.when(pl.col(pl.Utf8).is_not_null())
            .then(pl.col(pl.Utf8)
             .str.to_uppercase()
             .str.replace_all('Á', 'A')
             .str.replace_all('É', 'E')
             .str.replace_all('Í', 'I')
             .str.replace_all('Ó', 'O')
             .str.replace_all('Ú', 'U')
             .str.replace_all('Ü', 'U'))
        .otherwise(pl.col(types))
        .keep_name()
        ])
    return dataframe

In [ ]:
def standardize_nulls(dataframe: pl.DataFrame) -> pl.DataFrame:
        '''From a Polars dataframe we replace specific values with nulls in all string and numeric columns'''
        dataframe = dataframe.with_columns([
            pl.when(pl.col(pl.Utf8).is_in(string_nulls))
                .then(None)
                .otherwise(pl.col(pl.Utf8))
                .keep_name(),
            pl.when(pl.col(pl.Int64).is_in(number_nulls))
                .then(None)
                .otherwise(pl.col(pl.Int64))
                .keep_name(),
        ])
        return dataframe

In [ ]:
def concat_address_columns(dataframe: pl.DataFrame) -> pl.DataFrame:
    '''From a Polars dataframe we concat address columns and create new fields'''
    return dataframe.with_columns([
        pl.concat_str([pl.col('address_street_type'), pl.col(
            'address_street')], sep=' ').alias('address_line_1'),
        pl.concat_str([pl.col('address_reference_type_1'), pl.col(
            'address_reference_street_1')], sep=' ').alias('address_reference_1'),
        pl.concat_str([pl.col('address_reference_type_2'), pl.col(
            'address_reference_street_2')], sep=' ').alias('address_reference_2'),
        pl.concat_str([pl.col('address_reference_type_3'), pl.col(
            'address_reference_street_3')], sep=' ').alias('address_reference_3'),
    ])

In [ ]:
def cast_dates(dataframe: pl.DataFrame) -> pl.DataFrame:
    '''From a Polars dataframe we cast dates in YYYY-mm-dd format'''
    dataframe = dataframe.with_columns ([
        pl.concat_str([
            pl.col('creation_date').str.replace(' ','-'),pl.lit('01')], sep ='-')
        .str.strptime(pl.Date, fmt="%F")
        .keep_name()])    
    return dataframe

In [ ]:
def transform(raw_data: pl.DataFrame):
    clean_data = (raw_data
                  .pipe(rename_columns)
                  .pipe(remove_accents)
                  .pipe(standardize_nulls)
                  .pipe(concat_address_columns)
                  .pipe(cast_dates)
                  )
    return clean_data